// sveltekit/src/lib/components/Formbricks.svelte
<script lang="ts">
  import { navigating } from '$app/stores';
  import type fbT from '@formbricks/js';
  import { onMount } from 'svelte';

  let formbricks: typeof fbT;

  onMount(() => {
    import('@formbricks/js').then((fb) => {
      formbricks = fb.default;
      formbricks.init({
        environmentId: 'clg6riezp0005lq0hzjimosc7',
        apiHost: 'https://app.formbricks.com',
        debug: true,
      });

      (window as any).formbricks = formbricks;
    });
  });

  $: if ($navigating) formbricks.registerRouteChange();
</script>

// nextjs-app/src/app/formbricks.tsx
"use client";
import formbricks from "@formbricks/js";
import { usePathname, useSearchParams } from "next/navigation";
import { useEffect } from "react";

export default function FormbricksProvider() {
  const pathname = usePathname();
  const searchParams = useSearchParams();

  useEffect(() => {
    formbricks.init({
      environmentId: "cllxhby3p0b1fmr0her1wkwtq",
      apiHost: "https://app.formbricks.com",
      debug: true, // remove when in production
    });
  }, []);

  useEffect(() => {
    formbricks?.registerRouteChange();
  }, [pathname, searchParams]);

  return null;
}
